# Generated by Django 5.2 on 2026-05-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_employeeprofile_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('dependencia', 'Dependencia'), ('empresa_externa', 'Empresa Externa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('admin', 'Administrator')], max_length=10),
        ),
    ]
