# Generated by Django 5.2 on 2026-05-31 20:58

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_tipo_empresa_alter_user_role'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separe los tags con comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
