# Generated by Django 5.2 on 2026-06-07 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_employerprofile_privilegios'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'La cédula debe tener 8 dígitos')]),
        ),
    ]
