# Generated by Django 5.2 on 2026-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_employeeprofile_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('dependencia', 'Dependencia'), ('empresa_externa', 'Empresa')], max_length=20, null=True),
        ),
    ]
